(function(){
'use strict';
const app=document.getElementById('app');
const KEY='ielts100StateV1';
const defaults={completed:[],favorites:[],lastDay:1,notes:{},started:[]};
let state=load(); let filter='All';
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return {...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateFavCount()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function id(n){return String(n).padStart(3,'0')}
function toast(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.append(x);setTimeout(()=>x.remove(),2300)}
function updateFavCount(){document.getElementById('favCount').textContent=state.favorites.length}
function go(route){location.hash=route==='home'?'#home':route==='topics'?'#topics':'#day-'+id(route);window.scrollTo(0,0)}
function stats(){const done=state.completed.length;return {done,words:done*20,speaking:done*2,reading:done,pct:done}}
function card(t){const available=!!IELTS_DAYS[t.id],status=state.completed.includes(t.id)?'completed':state.started.includes(t.id)?'learning':'';return `<button class="topic-card ${available?'':'locked'}" ${available?`data-day="${t.id}"`:''} aria-label="${available?'打开':'尚未发布'} Day ${id(t.id)} ${esc(t.topic)}"><i class="status ${status}"></i><span class="num">DAY ${id(t.id)}</span><h3>${esc(t.topic)}</h3><p>${esc(t.topicCN)} · ${esc(t.category)}${available?'':' · Coming soon'}</p></button>`}
function home(){const s=stats(),last=IELTS_DAYS[state.lastDay]?state.lastDay:1;app.innerHTML=`<section class="hero"><p class="eyebrow">100-Day Mastery</p><h1>Build English you can actually use.</h1><p class="lead">Vocabulary · Speaking · Writing · Reading<br>围绕真实主题建立完整学习闭环，从基础表达逐步走向 IELTS 7+。</p><div class="hero-actions"><button class="primary" data-day="${last}">Continue Day ${id(last)}</button><button class="ghost" data-route="topics">Explore topic map</button></div></section><section class="progress-panel"><div class="progress-main"><small>YOUR PROGRESS</small><strong>Day ${String(Math.min(s.done+1,100)).padStart(2,'0')} / 100</strong><div class="progress-track"><div class="progress-fill" style="width:${s.pct}%"></div></div></div><div class="metric"><small>Topics completed</small><strong>${s.done}</strong></div><div class="metric"><small>Words learned</small><strong>${s.words}</strong></div><div class="metric"><small>Speaking practices</small><strong>${s.speaking}</strong></div><div class="metric"><small>Reading passages</small><strong>${s.reading}</strong></div></section><div class="section-head"><div><p class="eyebrow">Begin the journey</p><h2>First lessons</h2></div><p>100 complete lessons · Ready for daily study</p></div><section class="topic-grid">${IELTS_TOPICS.slice(0,8).map(card).join('')}</section>`;bindCommon()}
function topics(){const cats=['All',...new Set(IELTS_TOPICS.map(x=>x.category))];app.innerHTML=`<div class="section-head"><div><p class="eyebrow">Curriculum</p><h1>100-Day Topic Map</h1><p class="lead">主题从日常生活逐步过渡到全球议题。前三天内容已完成，其余主题待审核后发布。</p></div></div><div class="controls"><input class="search" id="topicSearch" type="search" placeholder="Search topics / 搜索主题" aria-label="搜索主题"><div class="chips">${cats.map(c=>`<button class="chip ${c==='All'?'active':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><section id="topicGrid" class="topic-grid">${IELTS_TOPICS.map(card).join('')}</section><div class="complete-wrap"><button id="resetBtn" class="ghost">Reset Progress · 重置进度</button></div>`;bindCommon();document.getElementById('topicSearch').addEventListener('input',renderFilter);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderFilter()});document.getElementById('resetBtn').onclick=()=>{if(confirm('确定要重置全部进度、收藏和笔记吗？此操作无法撤销。')&&confirm('再次确认：永久删除本设备上的全部学习记录？')){state={...defaults,completed:[],favorites:[],notes:{},started:[]};save();topics();toast('Progress reset')}}}
function renderFilter(){const q=(document.getElementById('topicSearch').value||'').trim().toLowerCase();document.getElementById('topicGrid').innerHTML=IELTS_TOPICS.filter(t=>(filter==='All'||t.category===filter)&&(`${t.topic} ${t.topicCN} ${t.category}`).toLowerCase().includes(q)).map(card).join('')||'<p class="empty">No topics found.</p>';bindCommon()}
const sectionNames=[['vocabulary','Vocabulary','核心词汇与搭配'],['paraphrases','Paraphrases','同义替换'],['sentences','Sentences','高分句型'],['expressions','Expressions','自然表达'],['mistakes','Mistakes','高频错误'],['writing','Writing','观点与论证'],['speaking','Speaking','口语练习'],['reading','Reading','主题阅读'],['notes','My Notes','我的笔记']];
function day(n){const d=IELTS_DAYS[n];if(!d){topics();return}state.lastDay=n;if(!state.started.includes(n))state.started.push(n);save();const fav=w=>state.favorites.includes(`${n}:${w}`);app.innerHTML=`<header class="day-header"><div><p class="eyebrow">DAY ${id(n)} · ${esc(d.category)}</p><h1>${esc(d.topic)}</h1><p class="day-cn">${esc(d.topicCN)}</p></div><button class="ghost" data-route="topics">← Topic map</button></header><div class="day-layout"><nav class="side-nav">${sectionNames.map(x=>`<a href="#${x[0]}">${x[1]}</a>`).join('')}</nav><div class="study-stack">
${study('vocabulary','Vocabulary & Collocations','核心词汇与搭配',`<div class="vocab-list">${d.vocabulary.map(v=>`<article class="vocab"><button class="icon-btn ${fav(v.word)?'saved':''}" data-fav="${esc(v.word)}" aria-label="收藏 ${esc(v.word)}">${fav(v.word)?'★':'☆'}</button><strong>${esc(v.word)}</strong><span class="ipa">${esc(v.ipa)}</span><div class="translation">${esc(v.meaning)}</div><div class="collocation">${esc(v.collocation)}<br><span class="translation">${esc(v.collocationCN)}</span></div></article>`).join('')}</div>`, '<button class="reveal" id="toggleCN">Hide Chinese</button>')}
${study('paraphrases','Synonyms & Paraphrases','同义替换',d.paraphrases.map(p=>`<div class="list-row"><strong>${esc(p.base)}</strong> <span class="arrow">→</span> ${p.options.map(esc).join(' · ')}<p class="example">${esc(p.note)}</p></div>`).join(''))}
${study('sentences','High-score Sentence Patterns','高分句型',d.sentences.map(s=>`<div class="list-row"><strong>${esc(s.pattern)}</strong><div class="translation">${esc(s.cn)}</div><p class="example">${esc(s.example)}</p></div>`).join(''))}
${study('expressions','Natural Expressions','自然口语与地道表达',d.expressions.map(e=>`<div class="list-row"><strong>${esc(e.text)}</strong><div class="translation">${esc(e.cn)}</div><p class="example">${esc(e.example)}</p></div>`).join(''))}
${study('mistakes','Common Mistakes','高频错误',d.mistakes.map(m=>`<div class="list-row"><div class="wrong">✕ ${esc(m.wrong)}</div><div class="correct">✓ ${esc(m.correct)}</div><p class="example">Why? ${esc(m.why)}</p></div>`).join(''))}
${study('writing','Writing Ideas & Arguments','写作观点与论证',d.writingIdeas.map((w,i)=>`<details><summary><span class="tag">Viewpoint ${i+1}</span>${esc(w.viewpoint)}</summary><h3>${esc(w.topicSentence)}</h3><div class="collocation-pills">${w.collocations.map(c=>`<span>${esc(c)}</span>`).join('')}</div><p>${esc(w.argument)}</p></details>`).join(''))}
${study('speaking','Speaking Practice','口语练习与参考答案',d.speaking.map((s,i)=>`<details><summary><span class="tag">${esc(s.part)}</span>${esc(s.question)}</summary><p class="example">先录下自己的回答，再展开参考答案。</p><p>${esc(s.answer)}</p></details>`).join(''))}
${study('reading','IELTS-style Reading','雅思风格主题阅读',`<article class="reading"><h3>${esc(d.reading.title)}</h3>${d.reading.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</article><div id="questions">${d.reading.questions.map((q,i)=>`<div class="question"><span class="tag">${esc(q.type)}</span><strong>${i+1}. ${esc(q.prompt)}</strong>${q.options?`<ol type="A">${q.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol>`:''}<div class="answer-box"><strong>Answer: ${esc(q.answer)}</strong><br>${esc(q.explanation)}</div></div>`).join('')}</div><button class="reveal" id="showAnswers">Show Answers</button>`)}
${study('notes','My Notes','我的笔记',`<textarea class="notes" id="notesBox" placeholder="记录新词、口语答案、写作观点或错题……">${esc(state.notes[n]||'')}</textarea><p class="example">Automatically saved on this device · 自动保存于本设备</p>`)}
<section class="study-card complete-wrap"><h2>${state.completed.includes(n)?'Day completed ✓':'Ready to finish?'}</h2><p>完成状态会保存在此设备上，你可以随时回来复习。</p><button class="primary" id="completeDay">${state.completed.includes(n)?'Completed · Mark as learning':'✓ Complete Day'}</button></section></div></div>`;
bindCommon();document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const k=`${n}:${b.dataset.fav}`,i=state.favorites.indexOf(k);i<0?state.favorites.push(k):state.favorites.splice(i,1);save();b.classList.toggle('saved',i<0);b.textContent=i<0?'★':'☆'});document.getElementById('toggleCN').onclick=e=>{const hide=e.target.textContent.startsWith('Hide');document.querySelectorAll('#vocabulary .translation').forEach(x=>x.hidden=hide);e.target.textContent=hide?'Show Chinese':'Hide Chinese'};document.getElementById('showAnswers').onclick=e=>{document.getElementById('questions').classList.toggle('answers-visible');e.target.textContent=document.getElementById('questions').classList.contains('answers-visible')?'Hide Answers':'Show Answers'};document.getElementById('notesBox').addEventListener('input',e=>{state.notes[n]=e.target.value;save()});document.getElementById('completeDay').onclick=()=>{const i=state.completed.indexOf(n);i<0?state.completed.push(n):state.completed.splice(i,1);save();day(n);toast(i<0?'Day completed — well done!':'Marked as learning')};}
function study(key,en,cn,body,action=''){return `<section class="study-card" id="${key}"><header><div><h2>${en}</h2><div class="cn-label">${cn}</div></div>${action}</header>${body}</section>`}
function favorites(){const rows=state.favorites.map(k=>{const [n,w]=k.split(':');const d=IELTS_DAYS[n],v=d&&d.vocabulary.find(x=>x.word===w);return v?`<article class="vocab"><strong>${esc(v.word)}</strong><span class="ipa">${esc(v.ipa)}</span><div class="translation">${esc(v.meaning)}</div><div class="collocation">Day ${id(n)} · ${esc(v.collocation)}<br>${esc(v.collocationCN)}</div></article>`:''}).join('');app.innerHTML=`<div class="section-head"><div><p class="eyebrow">Review bank</p><h1>Favorite Vocabulary</h1><p class="lead">你收藏的词汇集中在这里，数据仅保存在当前设备。</p></div></div>${rows?`<section class="vocab-list">${rows}</section>`:'<div class="empty">还没有收藏词汇。打开任一课程，点击单词卡片上的 ☆ 即可收藏。</div>'}`}
function bindCommon(){document.querySelectorAll('[data-day]').forEach(x=>x.onclick=()=>go(+x.dataset.day));document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>go(x.dataset.route))}
function route(){document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));const h=location.hash||'#home';if(h==='#home'){home();document.querySelector('[data-route="home"]').classList.add('active')}else if(h==='#topics'){topics();document.querySelector('[data-route="topics"]').classList.add('active')}else if(h==='#favorites')favorites();else{const m=h.match(/^#day-(\d{3})/);m?day(+m[1]):home()}app.focus({preventScroll:true})}
document.getElementById('favoritesBtn').onclick=()=>{location.hash='#favorites'};window.addEventListener('hashchange',route);updateFavCount();route();
})();
