const fs=require('fs'),path=require('path'),root=path.join(__dirname,'..'),staged={};
for(const f of ['manual-days-081-087.js','manual-days-088-093.js','manual-days-094-100.js','manual-days-095-097.js','manual-days-098-100.js','manual-days-081-100-editorial.js'])Object.assign(staged,require(path.join(root,'content',f)));
const days=[];for(let id=81;id<=100;id++){if(!staged[id])throw new Error(`Missing staged Day ${id}`);days.push(staged[id])}
const previous=[];for(let id=4;id<=80;id++)previous.push(JSON.parse(fs.readFileSync(path.join(root,'data',`day-${String(id).padStart(3,'0')}.json`),'utf8')));
const errors=[],warnings=[],types={},readingWords={};
const tokens=s=>String(s).toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(Boolean),sh=(s,n=3)=>{const w=tokens(s),r=new Set();for(let i=0;i<=w.length-n;i++)r.add(w.slice(i,i+n).join(' '));return r},jac=(a,b)=>{let x=0;for(const k of a)if(b.has(k))x++;return x/(a.size+b.size-x||1)},maxPair=(items,get,n=3)=>{let b={days:[],score:0};for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){let s=jac(sh(get(items[i]),n),sh(get(items[j]),n));if(s>b.score)b={days:[items[i].id,items[j].id],score:s}}return b};
for(const d of days){for(const [k,n] of Object.entries({vocabulary:20,paraphrases:8,sentences:3,expressions:5,mistakes:3,writingIdeas:2,speaking:2}))if(!d[k]||d[k].length!==n)errors.push(`Day ${d.id} ${k} expected ${n}`);for(const v of d.vocabulary||[])if(!v.word||!v.ipa||!v.meaning||!v.collocation||!v.collocationCN)errors.push(`Day ${d.id} vocabulary field`);for(const p of d.paraphrases||[])if(!p.base||!p.options||p.options.length!==3||!p.note)errors.push(`Day ${d.id} paraphrase field`);for(const s of d.sentences||[])if(!s.pattern||!s.cn||!s.example||s.pattern.includes('...')||/connected with|value judgement|comparative standard|public benefit|reliability claim|source action|concealed purpose|recovery clause|non-finite action/i.test(s.pattern))errors.push(`Day ${d.id} abstract/invalid pattern: ${s.pattern}`);for(const m of d.mistakes||[])if(!m.wrong||!m.correct||!m.why)errors.push(`Day ${d.id} mistake field`);for(const w of d.writingIdeas||[]){let n=(w.argument.match(/[.!?](?:\s|$)/g)||[]).length;if(!w.collocations||w.collocations.length!==4||n<4||n>5)errors.push(`Day ${d.id} writing structure ${n}`)}if(d.speaking?.[0]?.part!=='Part 2'||d.speaking?.[1]?.part!=='Part 3')errors.push(`Day ${d.id} speaking parts`);for(const s of d.speaking||[])if(tokens(s.answer).length<75)warnings.push(`Day ${d.id} ${s.part} ${tokens(s.answer).length} words`);let wc=tokens(d.reading?.paragraphs?.join(' ')).length;readingWords[d.id]=wc;if(wc<300||wc>400)errors.push(`Day ${d.id} reading ${wc}`);if(!d.reading||d.reading.paragraphs.length<3||d.reading.paragraphs.length>5||d.reading.questions.length!==3)errors.push(`Day ${d.id} reading structure`);for(const q of d.reading?.questions||[]){types[q.type]=(types[q.type]||0)+1;if(!q.answer||!q.explanation)errors.push(`Day ${d.id} question field`);if(q.type==='Multiple Choice'&&(!q.options||q.options.length!==4))errors.push(`Day ${d.id} MCQ`)}}
const combined=[...previous,...days],reading=maxPair(days,d=>d.reading.paragraphs.join(' ')),writing=maxPair(days,d=>d.writingIdeas.map(x=>x.argument).join(' ')),speaking=maxPair(days,d=>d.speaking.map(x=>x.question+' '+x.answer).join(' '),2),allReading=maxPair(combined,d=>d.reading.paragraphs.join(' '));for(const [n,r] of Object.entries({reading,writing,speaking,allReading}))if(r.score>.45)errors.push(`${n} similarity ${(r.score*100).toFixed(1)}% Day ${r.days.join('/')}`);
for(const key of ['sentences','expressions','speaking']){const seen=new Map();for(const d of combined)for(const x of d[key]||[]){const val=tokens(x.pattern||x.text||x.question).join(' ');if(seen.has(val)&&(seen.get(val)>=81||d.id>=81))errors.push(`${key} duplicate Day ${seen.get(val)}/${d.id}: ${val}`);else seen.set(val,d.id)}}
const report={passed:!errors.length,scope:'Staged Day 081–100; earlier days read-only except approved Day 061–080 corrections',errors,warnings,metrics:{readingWords,questionTypes:types,readingMaxSimilarity:{days:reading.days,percent:+(reading.score*100).toFixed(2)},writingMaxSimilarity:{days:writing.days,percent:+(writing.score*100).toFixed(2)},speakingMaxSimilarity:{days:speaking.days,percent:+(speaking.score*100).toFixed(2)},allReadingMaxSimilarity:{days:allReading.days,percent:+(allReading.score*100).toFixed(2)}}};fs.writeFileSync(path.join(root,'tools','qa-stage-081-100.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exit(errors.length?1:0);
